name: "vVAE"
n_gpu: 1
arch:
  _target_: hw_vae.model.vVAE

train_ds:
  _target_: hw_vae.datasets_.VAEDataset
  part: "train"
  data_path: "/kaggle/input/anime-faces/data"

data:
  train:
    batch_size: 32
    num_workers: 6
    datasets: 
      - ${train_ds}

optimizer:
  _target_: torch.optim.Adam
  lr: 0.005
  weight_decay: 1e-4

lr_scheduler:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.95
    
Loss:
  _target_: hw_vae.loss.VLBLoss

Metric:
  _target_: hw_vae.metrics.SSIMMetric


trainer: 
  epochs: 120
  save_dir: "saved/"
  save_period: 3
  verbosity: 2
  monitor: "off"
  early_stop: 500
  visualize: "wandb"
  wandb_project: "VAE_project"
  run_name: "VAE"
  sample_rate: 16000
  len_epoch: 1500
  log_step: 50
  grad_norm_clip: 10
  finetune: false
