name: "vVAE"
n_gpu: 1
arch:
  _target_: hw_vae.model.DCGAN

train_ds:
  _target_: hw_vae.datasets_.GANDataset
  part: "train"
  data_path: "/kaggle/input/anime-faces/data"

data:
  train:
    batch_size: 32
    num_workers: 6
    datasets: 
      - ${train_ds}

g_optimizer:
  _target_: torch.optim.Adam
  lr: 0.0002
  betas: [0.5, 0.999]

d_optimizer:
  _target_: torch.optim.SGD
  lr: 3e-4
 
Loss:
  _target_: hw_vae.loss.GANLoss

Metric:
  _target_: hw_vae.metrics.SSIMMetric


trainer: 
  epochs: 120
  save_dir: "saved/"
  save_period: 10
  verbosity: 2
  monitor: "off"
  early_stop: 500
  visualize: "wandb"
  wandb_project: "VAE_project"
  run_name: "VAE"
  sample_rate: 16000
  len_epoch: 1000
  log_step: 50
  grad_norm_clip: 1000
  finetune: false
